@rem call setenv producer
call setenv client

@cd %ABSPATH2CLASSES%
@cls

java -cp %CLASSPATH% -Djava.security.policy=%CLIENT_SECURITY_POLICY% -Djava.rmi.server.codebase=%SERVER_CODEBASE% -D%JAVAPACKAGEROLE%.codebase=%CLIENT_CODEBASE% -D%JAVAPACKAGE%.servicename=%SERVICE_NAME_ON_REGISTRY% %JAVAPACKAGEROLE%.%CLIENT_CLASS% %HOST% %REGISTRY_PORT% %SERVICE_NAME_ON_REGISTRY% %BROKER_PORT% %BROKER_QUEUE%

@cd %ABSPATH2SRC%\%JAVASCRIPTSPATH%



