@SET SCRIPT_ROLE=%1

@Set USERNAME=jorgerocha

@Set WORKDRIVE=C
@Set JDK=C:\\Program Files\\Java\\jdk-16.0.1

@Set JAVAPROJ_NAME=FroggerGame

@set JAVAPROJ=D:\\Development\\IntelliJProjects\\SD_23144\
@Set PACKAGE=frogger
@Set PACKAGE_PREFIX=edu.ufp.inf.sd.project
@Set PACKAGE_PREFIX_FOLDERS=edu/ufp/inf/sd/project

@Set SERVICE_NAME_ON_REGISTRY=FroggerService

@Set SERVER_CLASS=Server
@Set CLIENT_CLASS=Client

@Set SERVANT_IMPL_CLASS_POSTFIX=Impl

@Set QUEUE_NAME_PREFIX=frogger
@Set EXCHANGE_NAME_PREFIX=frogger


@Set HOST=localhost

@Set REGISTRY_HOST=%HOST%
@Set REGISTRY_PORT=1099

@Set BROKER_HOST=%HOST%
@Set BROKER_PORT=5672

@Set SERVER_RMI_HOST=%HOST%
@Set SERVER_RMI_PORT=1098
@Set SERVER_CODEBASE_HOST=%HOST%
@Set SERVER_CODEBASE_PORT=8000
@Set CLIENT_RMI_HOST=%HOST%
@Set CLIENT_RMI_PORT=1097
@Set CLIENT_CODEBASE_HOST=%HOST%
@Set CLIENT_CODEBASE_PORT=8000

@Set BROKER_QUEUE=%QUEUE_NAME_PREFIX%_queue
@Set BROKER_EXCHANGE=%EXCHANGE_NAME_PREFIX%_exchange
@Set BROKER_SERVICE_URL=http://%BROKER_HOST%:%BROKER_PORT%

@Set JAVAPACKAGE=%PACKAGE_PREFIX%.%PACKAGE%
@Set JAVAPACKAGEROLE=%PACKAGE_PREFIX%.%PACKAGE%.%SCRIPT_ROLE%
@Set JAVAPACKAGEPATH=%PACKAGE_PREFIX_FOLDERS%/%PACKAGE%/%SCRIPT_ROLE%
@Set JAVASCRIPTSPATH=%PACKAGE_PREFIX_FOLDERS%/%PACKAGE%/runscripts
@Set JAVASECURITYPATH=edu\\ufp\\inf\\sd\\project\\%PACKAGE%\\securitypolicies

@Set SERVICE_NAME=%SERVICE_PREFIX%Service
@Set SERVICE_URL=rmi://%REGISTRY_HOST%:%REGISTRY_PORT%/%SERVICE_NAME%

@Set SERVANT_ACTIVATABLE_IMPL_CLASS=%JAVAPACKAGEROLE%.%SERVER_CLASS_PREFIX%%SERVANT_ACTIVATABLE_IMPL_CLASS_POSTFIX%
@Set SERVANT_PERSISTENT_STATE_FILENAME=%SERVICE_PREFIX%Persistent.State

@Set PATH=%PATH%;.;%JDK%\bin


@Set JAVAPROJ_CLASSES=out\\production\\%JAVAPROJ_NAME%\\
@Set JAVAPROJ_CLASSES_FOLDER=%JAVAPROJ%\\%JAVAPROJ_CLASSES%
@Set JAVAPROJ_SRC=src
@Set JAVAPROJ_DIST=out\\artifacts\\%JAVAPROJ_NAME%\\
@Set JAVAPROJ_DIST_LIB=lib
@set JAVAPROJ_DIST_FOLDER=%JAVAPROJ%\%JAVAPROJ_DIST%
@set JAVAPROJ_JAR_FILE=%JAVAPROJ_NAME%.jar
@Set JAVA_LIB_FOLDER=%JAVAPROJ%\\%JAVAPROJ_DIST_LIB%
@Set JAVA_RABBITMQ_TOOLS=%JAVA_LIB_FOLDER%\\amqp-client-5.11.0.jar;%JAVA_LIB_FOLDER%\\slf4j-api-1.7.30.jar;%JAVA_LIB_FOLDER%\\slf4j-simple-1.7.30.jar


@Set CLASSPATH=.;%JAVAPROJ_JAR_FILE%;%JAVA_RABBITMQ_TOOLS%;%JAVAPROJ_CLASSES_FOLDER%
@Set ABSPATH2CLASSES=%JAVAPROJ%\%JAVAPROJ_CLASSES%
@Set ABSPATH2DIST=%JAVAPROJ%/%JAVAPROJ_DIST%
@Set ABSPATH2SRC=%JAVAPROJ%/%JAVAPROJ_SRC%

@Set SERVER_CODEBASE=http://%SERVER_CODEBASE_HOST%:%SERVER_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%
@Set CLIENT_CODEBASE=http://%CLIENT_CODEBASE_HOST%:%CLIENT_CODEBASE_PORT%/%JAVAPROJ_JAR_FILE%

@Set SERVER_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\serverAllPermition.policy
@Set CLIENT_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\clientAllPermition.policy
@Set SETUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\setup.policy
@Set RMID_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\rmid.policy
@Set GROUP_SECURITY_POLICY=file:///%JAVAPROJ%\\%JAVAPROJ_SRC%\\%JAVASECURITYPATH%\\group.policy